name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24''
        cache: 'npm'
    - run: cp configs/exampleconfig.json configs/config.json
    - run: echo "[]" > configs/accounts.json
    - run: npm ci
    - run: npx tsc

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24''
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
